name: sleep_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dotenv: ^4.2.0
  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  meta: ^1.12.0
  mongo_dart: ^0.10.2
  realm: ^2.3.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
